project:
  type: website

website:
  title: "De.KCD - Registry of Data Management Platforms"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

  sidebar:
    style : "docked"
    search: true
    contents:
        - pages/formats.qmd
        - pages/DataManagement_MajorPlatforms.qmd
        - pages/DataManagement_MediumPlatforms.qmd
        - pages/DataManagement_UsefulToolsAndPlatforms.qmd
        - pages/DataManagement_Ontologies.qmd
        - pages/DataManagement_Taxonomies.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



